"""Unprivileged locked Web Portal shell for the VRhotspot Flatpak."""

from .app import (
    APP_ID,
    APP_NAME,
    MAX_LIVE_SMOKE_JSON_BYTES,
    MAX_SMOKE_JSON_BYTES,
    WEBKIT_GI_NAMESPACE,
    WEBKIT_GI_VERSION,
    WEB_PORTAL_ORIGIN,
    WEB_PORTAL_URL,
    build_initial_model,
    build_smoke_payload,
    is_approved_web_portal_uri,
    main,
    render_smoke_json,
    run_live_pairing_smoke_json,
    run_tray,
    run_web_portal_shell,
)
from .tray import (
    ICON_NAMES,
    StatusNotifierBackend,
    TrayMenuItem,
    TrayMenuModel,
    TrayRuntime,
    WindowLifecycleController,
    build_tray_menu_model,
)

__all__ = [
    "APP_ID",
    "APP_NAME",
    "MAX_LIVE_SMOKE_JSON_BYTES",
    "MAX_SMOKE_JSON_BYTES",
    "WEBKIT_GI_NAMESPACE",
    "WEBKIT_GI_VERSION",
    "WEB_PORTAL_ORIGIN",
    "WEB_PORTAL_URL",
    "build_initial_model",
    "build_smoke_payload",
    "is_approved_web_portal_uri",
    "main",
    "render_smoke_json",
    "run_live_pairing_smoke_json",
    "run_tray",
    "run_web_portal_shell",
    "ICON_NAMES",
    "StatusNotifierBackend",
    "TrayMenuItem",
    "TrayMenuModel",
    "TrayRuntime",
    "WindowLifecycleController",
    "build_tray_menu_model",
]
